baseURL: "https://drishanbanerjee.github.io/"
title: Drishan Banerjee
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Job Market Paper
          url: jmp/
          weight: 1
        - name: Papers
          url: papers/
          weight: 2
        - name: Teaching
          url: teaching/
          weight: 3
        - name: CV
          url: cv.pdf
          weight: 4

params:
    description: "This website hosts Drishan Banerjee's research papers, teaching, curriculum vitae, and contact information."
    author: Drishan Banerjee
    # googleAnalyticsID: G-XXXXX
    DateFormat: January 2006
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: [papers]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Drishan Banerjee
          subtitle: "I am a PhD candidate in economics at the University of California, Santa Cruz. My research interests are in macroeconomics and international finance."
          imageUrl: picture.jpeg
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Job Market Paper
              url: jmp/
            - name: Papers
              url: papers/
            - name: Teaching
              url: teaching/
            - name: CV
              url: cv.pdf

    # Icons shown under your bio. To add one, remove the "#" in front of
    # its two lines and replace the placeholder link with your own.
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:drbanerj@ucsc.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=6dsLX_gAAAAJ
        - name: LinkedIn
          url: https://www.linkedin.com/in/drishanbanerjee/
        - name: GitHub
          url: https://github.com/drishanbanerjee

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: Drishan Banerjee
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
